//民族列表
export const NATIONS = [
  '汉族',
  '蒙古族',
  '回族',
  '藏族',
  '维吾尔族',
  '苗族',
  '彝族',
  '壮族',
  '布依族',
  '朝鲜族',
  '满族',
  '侗族',
  '瑶族',
  '白族',
  '土家族',
  '哈尼族',
  '哈萨克族',
  '傣族',
  '黎族',
  '傈僳族',
  '佤族',
  '畲族',
  '高山族',
  '拉祜族',
  '水族',
  '东乡族',
  '纳西族',
  '景颇族',
  '柯尔克孜族',
  '土族',
  '达斡尔族',
  '仫佬族',
  '羌族',
  '布朗族',
  '撒拉族',
  '毛南族',
  '仡佬族',
  '锡伯族',
  '阿昌族',
  '普米族',
  '塔吉克族',
  '怒族',
  '乌孜别克族',
  '俄罗斯族',
  '鄂温克族',
  '德昂族',
  '保安族',
  '裕固族',
  '京族',
  '塔塔尔族',
  '独龙族',
  '鄂伦春族',
  '赫哲族',
  '门巴族',
  '珞巴族',
  '基诺族',
];

// 邮箱后缀列表
export const EMAIL_FILL = [
  'qq.com',
  '163.com',
  '126.com',
  'sina.com',
  'hotmail.com',
  'gmail.com',
  'sohu.com',
];

// 性别列表
export const SEX_LIST = ['--', '男', '女', '--'];

// 工作性质列表
export const WORK_TYPE_LIST = [
  '全职',
  '实习',
  '兼职',
  '劳务派遣',
  '劳务外包',
  '钟点工',
  '退休返聘',
  '无类型',
];

// 工作年限列表
export const WORK_NUM_LIST = ['全部', '1年以内', '1～3年', '3～5年', '5～10年', '10年以上'];

// 星级评分文案
export const STAR_TEXT = ['很差', '一般', '满意', '非常满意', '无可挑剔'];

// 证件类型
export const CARD_TYPE = ['身份证', '港澳居民来往内地通行证', '台湾人民来往大陆通行证', '外国护照'];
//政治面貌
export const PILITICAL_CLIMATE = ['党员', '团员', '群众', '其他'];

//婚姻状态列表
// export const MARRIAGE_STUATS = ['未婚', '已婚', '离异', '丧偶', '分居'];

//紧急联系人关系
// export const EMERGENEY_CONTACT = ['父母', '配偶', '子女', '亲属', '朋友', '同事', '其他'];

// 反馈状态文字
// export const STATUS_TEXT = ['已反馈', '部分反馈', '未反馈', '面试已取消'];
// 邮箱验证
export const REG_EMAIL = /\w[-\w.+]*@([A-Za-z0-9][-A-Za-z0-9]+\.)+[A-Za-z]{2,14}/g;
export const SUFFIX = ['vip.163.com', 'vip.126.com', '188.com', '163.com', '126.com', 'yeah.net'];

export const menu = [
  {
    key: 'setting',
    url: '/setting/index',
    name: '前处理管理',
    icon: 'T8-shezhi-weixuanzhong',
    selIcon: 'T8-shezhi-xuanzhong',
    children: [
      {
        key: 'setting',
        url: '/setting/index',
        name: '样本登记',
        icon: 'T8-shezhi-weixuanzhong',
        selIcon: 'T8-shezhi-xuanzhong',
        children: [
          {
            key: 'setting',
            url: '/preProcessingMag/sampleRegistration',
            name: '样本登记列表',
            icon: 'T8-shezhi-weixuanzhong',
            selIcon: 'T8-shezhi-xuanzhong',
            children: [],
          },
          {
            key: 'setting',
            url: '/preProcessingMag/applicationForm',
            name: '申请单核对',
            icon: 'T8-shezhi-weixuanzhong',
            selIcon: 'T8-shezhi-xuanzhong',
            children: [],
          },
          {
            key: 'setting',
            url: '/setting/index',
            name: '扫码录入',
            icon: 'T8-shezhi-weixuanzhong',
            selIcon: 'T8-shezhi-xuanzhong',
            children: [],
          },
        ],
      },
      {
        key: 'setting',
        url: '/preProcessingMag/sampleReceipt',
        name: '样本签收',
        icon: 'T8-shezhi-weixuanzhong',
        selIcon: 'T8-shezhi-xuanzhong',
      },
      {
        key: 'setting',
        url: '/preProcessingMag/receiptForm',
        name: '签收单',
        icon: 'T8-shezhi-weixuanzhong',
        selIcon: 'T8-shezhi-xuanzhong',
      },
      {
        key: 'setting',
        url: '/preProcessingMag/sampleSortingt',
        name: '样本分检',
        icon: 'T8-shezhi-weixuanzhong',
        selIcon: 'T8-shezhi-xuanzhong',
        children: [],
      },
      {
        key: 'setting',
        url: '/preProcessingMag/sampleHandover',
        name: '样本交接',
        icon: 'T8-shezhi-weixuanzhong',
        selIcon: 'T8-shezhi-xuanzhong',
        children: [],
      },
      {
        key: 'setting',
        url: '/preProcessingMag/bloodSeparationMag',
        name: '分血管理',
        icon: 'T8-shezhi-weixuanzhong',
        selIcon: 'T8-shezhi-xuanzhong',
        children: [],
      },
      {
        key: 'setting',
        url: '',
        name: '拒检管理',
        icon: 'T8-shezhi-weixuanzhong',
        selIcon: 'T8-shezhi-xuanzhong',
        children: [],
      },
      {
        key: 'setting',
        url: '',
        name: '延迟管理',
        icon: 'T8-shezhi-weixuanzhong',
        selIcon: 'T8-shezhi-xuanzhong',
        children: [],
      },
      {
        key: 'setting',
        url: '',
        name: '加减项管理',
        icon: 'T8-shezhi-weixuanzhong',
        selIcon: 'T8-shezhi-xuanzhong',
        children: [],
      },
      {
        key: 'setting',
        url: '',
        name: '委托检验管理',
        icon: 'T8-shezhi-weixuanzhong',
        selIcon: 'T8-shezhi-xuanzhong',
        children: [
          {
            key: 'setting',
            url: '',
            name: '外送样本移交',
            icon: 'T8-shezhi-weixuanzhong',
            selIcon: 'T8-shezhi-xuanzhong',
          },
          {
            key: 'setting',
            url: '',
            name: '外送样本对账明细',
            icon: 'T8-shezhi-weixuanzhong',
            selIcon: 'T8-shezhi-xuanzhong',
          },
          {
            key: 'setting',
            url: '',
            name: '外送样本对账统计',
            icon: 'T8-shezhi-weixuanzhong',
            selIcon: 'T8-shezhi-xuanzhong',
          },
          {
            key: 'setting',
            url: '',
            name: '外送样本管理',
            icon: 'T8-shezhi-weixuanzhong',
            selIcon: 'T8-shezhi-xuanzhong',
          },
        ],
      },
      {
        key: 'setting',
        url: '',
        name: '样本签收统计',
        icon: 'T8-shezhi-weixuanzhong',
        selIcon: 'T8-shezhi-xuanzhong',
      },
      {
        key: 'setting',
        url: '',
        name: '送检样本登记表',
        icon: 'T8-shezhi-weixuanzhong',
        selIcon: 'T8-shezhi-xuanzhong',
      },
      {
        key: 'setting',
        url: '',
        name: '样本交接统计表',
        icon: 'T8-shezhi-weixuanzhong',
        selIcon: 'T8-shezhi-xuanzhong',
      },
    ],
  },
  {
    name: '普检管理',
    icon: null,
    url: '/generalInspectionMag',
    key: '2',
    children: [
      {
        name: '上机任务分配-单仪器',
        icon: null,
        url: '/generalInspectionMag/singleInstruments',
        children: [],
        key: '21',
      },
      {
        name: '上机任务分配-多仪器',
        icon: null,
        url: '/generalInspectionMag/multiInstrument',
        key: '3',
      },
      {
        name: '上机任务分配-手工实验',
        icon: null,
        url: '/generalInspectionMag/manualExperiments',
        key: '3',
      },
      {
        name: '报告数据管理',
        icon: null,
        url: '/generalInspectionMag/reportDataMag',
        key: '3',
      },
      {
        name: '报告审核',
        icon: null,
        url: '/home',
        key: '3',
      },
      {
        name: '结果批录入',
        icon: null,
        url: '/home',
        key: '3',
      },
      {
        name: '结果批调整',
        icon: null,
        url: '/home',
        key: '3',
      },
      {
        name: '结果批删除',
        icon: null,
        url: '/home',
        key: '3',
      },
      {
        name: '结果合并',
        icon: null,
        url: '/home',
        key: '3',
      },
      {
        name: '糖耐量合并',
        icon: null,
        url: '/home',
        key: '3',
      },
      {
        name: '胰岛素合并',
        icon: null,
        url: '/home',
        key: '3',
      },
      {
        name: '报告项目选择',
        icon: null,
        url: '/home',
        key: '3',
      },
      {
        name: '危急值处理',
        icon: null,
        url: '/home',
        key: '3',
      },
      {
        name: '失控管理',
        icon: null,
        url: '/home',
        key: '3',
      },
      {
        name: '任务单查询',
        icon: null,
        url: '/home',
        key: '3',
      },
    ],
  },
  {
    name: '申请单管理',
    icon: null,
    url: '/home',
    key: '2',
    children: [
      {
        name: '申请单查询',
        icon: null,
        url: '/applicationFormMsg/applyFormSearch',
        children: [],
        key: '21',
      },
      {
        name: '申请单分类',
        icon: null,
        url: '/home',
        key: '3',
      },
      {
        name: '申请单导入/导出',
        icon: null,
        url: '/home',
        key: '3',
      },
      {
        name: '申请单汇总统计',
        icon: null,
        url: '/home',
        key: '3',
      },
      {
        name: '申请单明细统计',
        icon: null,
        url: '/home',
        key: '3',
      },
    ],
  },
  {
    key: 'setting',
    url: '/setting/index',
    name: '客服管理',
    icon: 'T8-shezhi-weixuanzhong',
    selIcon: 'T8-shezhi-xuanzhong',
    children: [
      {
        key: 'setting',
        url: '/customerServiceMsg/consultationRegistration',
        name: '咨询单管理',
        icon: 'T8-shezhi-weixuanzhong',
        selIcon: 'T8-shezhi-xuanzhong',
        children: [],
      },
      {
        key: 'setting',
        url: '/customerServiceMsg/consultationFormStatistics',
        name: '咨询单统计',
        icon: 'T8-shezhi-weixuanzhong',
        selIcon: 'T8-shezhi-xuanzhong',
        children: [],
      },
      {
        key: 'setting',
        url: '/setting/index',
        name: '申请项目字典',
        icon: 'T8-shezhi-weixuanzhong',
        selIcon: 'T8-shezhi-xuanzhong',
        children: [],
      },
      {
        key: 'setting',
        url: '/setting/index',
        name: '申请项目价表',
        icon: 'T8-shezhi-weixuanzhong',
        selIcon: 'T8-shezhi-xuanzhong',
        children: [],
      },
      {
        key: 'setting',
        url: '/setting/index',
        name: '客户满意度调查表',
        icon: 'T8-shezhi-weixuanzhong',
        selIcon: 'T8-shezhi-xuanzhong',
        children: [],
      },
      {
        key: 'setting',
        url: '/setting/index',
        name: '复检样本记录表',
        icon: 'T8-shezhi-weixuanzhong',
        selIcon: 'T8-shezhi-xuanzhong',
        children: [],
      },
    ],
  },
  {
    key: 'setting',
    url: '/setting/index',
    name: '交接单管理',
    icon: 'T8-shezhi-weixuanzhong',
    selIcon: 'T8-shezhi-xuanzhong',
    children: [
      {
        key: 'setting',
        url: '/handoverMsg/handoverRegistration',
        name: '交接单登记',
        icon: 'T8-shezhi-weixuanzhong',
        selIcon: 'T8-shezhi-xuanzhong',
      },
      {
        key: 'setting',
        url: '/handoverMsg/handoverOrderProcess',
        name: '交接单处理',
        icon: 'T8-shezhi-weixuanzhong',
        selIcon: 'T8-shezhi-xuanzhong',
      },
      {
        key: 'setting',
        url: '/handoverMsg/handoverProcessCount',
        name: '交接单统计',
        icon: 'T8-shezhi-weixuanzhong',
        selIcon: 'T8-shezhi-xuanzhong',
      },
    ],
  },
  {
    // key: 'setting',
    // url: '/setting/index',
    name: '报告单管理',
    icon: 'T8-shezhi-weixuanzhong',
    selIcon: 'T8-shezhi-xuanzhong',
    children: [
      {
        key: 'reportMag',
        url: '/reportMag/reportReview',
        name: '报告单审核',
        icon: 'T8-shezhi-weixuanzhong',
        selIcon: 'T8-shezhi-xuanzhong',
      },
      {
        key: 'reportMag',
        url: '/reportMag/reportPrintByHospital',
        name: '报告单打印(按医院)',
        icon: 'T8-shezhi-weixuanzhong',
        selIcon: 'T8-shezhi-xuanzhong',
      },
      {
        key: 'setting',
        url: '/setting/index',
        name: '报告单打印(按科室)',
        icon: 'T8-shezhi-weixuanzhong',
        selIcon: 'T8-shezhi-xuanzhong',
      },
      {
        key: 'setting',
        url: '/setting/index',
        name: '报告单打印(按仪器)',
        icon: 'T8-shezhi-weixuanzhong',
        selIcon: 'T8-shezhi-xuanzhong',
      },
      {
        key: 'setting',
        url: '/reportMag/reportCompreQuery',
        name: '报告单综合查询',
        icon: 'T8-shezhi-weixuanzhong',
        selIcon: 'T8-shezhi-xuanzhong',
      },
      {
        key: 'setting',
        url: '/setting/index',
        name: '报告结果导入',
        icon: 'T8-shezhi-weixuanzhong',
        selIcon: 'T8-shezhi-xuanzhong',
      },
      {
        key: 'setting',
        url: '/setting/index',
        name: '报告单导出',
        icon: 'T8-shezhi-weixuanzhong',
        selIcon: 'T8-shezhi-xuanzhong',
      },
      {
        key: 'setting',
        url: '/setting/index',
        name: '报告单合并',
        icon: 'T8-shezhi-weixuanzhong',
        selIcon: 'T8-shezhi-xuanzhong',
      },
      {
        key: 'setting',
        url: '/setting/index',
        name: '历史报告回顾',
        icon: 'T8-shezhi-weixuanzhong',
        selIcon: 'T8-shezhi-xuanzhong',
      },
      {
        key: 'setting',
        url: '/setting/index',
        name: '延时报告查询',
        icon: 'T8-shezhi-weixuanzhong',
        selIcon: 'T8-shezhi-xuanzhong',
      },
      {
        key: 'setting',
        url: '/experTaskNavigation/task',
        name: '实验任务导航',
        icon: 'T8-shezhi-weixuanzhong',
        selIcon: 'T8-shezhi-xuanzhong',
      },
    ],
  },
  {
    key: 'setting',
    url: '/setting/index',
    name: '室内质控',
    icon: 'T8-shezhi-weixuanzhong',
    selIcon: 'T8-shezhi-xuanzhong',
    children: [
      {
        key: 'setting',
        url: '/indoorQualityControMsg/qualityControlPRJ',
        name: '质控项目定义',
        icon: 'T8-shezhi-weixuanzhong',
        selIcon: 'T8-shezhi-xuanzhong',
      },
      {
        key: 'setting',
        url: '/indoorQualityControMsg/qualityControlProduct',
        name: '质控品维护',
        icon: 'T8-shezhi-weixuanzhong',
        selIcon: 'T8-shezhi-xuanzhong',
      },
      {
        key: 'setting',
        url: '/setting/index',
        name: '质控靶值设定',
        icon: 'T8-shezhi-weixuanzhong',
        selIcon: 'T8-shezhi-xuanzhong',
      },
      {
        key: 'setting',
        url: '/setting/index',
        name: '质控结果规则转换',
        icon: 'T8-shezhi-weixuanzhong',
        selIcon: 'T8-shezhi-xuanzhong',
      },
      {
        key: 'setting',
        url: '/setting/index',
        name: '质控常见文字描述',
        icon: 'T8-shezhi-weixuanzhong',
        selIcon: 'T8-shezhi-xuanzhong',
      },
      {
        key: 'setting',
        url: '/setting/index',
        name: '质控规则(仪器)',
        icon: 'T8-shezhi-weixuanzhong',
        selIcon: 'T8-shezhi-xuanzhong',
      },
      {
        key: 'setting',
        url: '/setting/index',
        name: '质控规则(项目)',
        icon: 'T8-shezhi-weixuanzhong',
        selIcon: 'T8-shezhi-xuanzhong',
      },
      {
        key: 'setting',
        url: '/setting/index',
        name: '仪器标本号质控对照',
        icon: 'T8-shezhi-weixuanzhong',
        selIcon: 'T8-shezhi-xuanzhong',
      },
      {
        key: 'setting',
        url: '/setting/index',
        name: '仪器数据维护',
        icon: 'T8-shezhi-weixuanzhong',
        selIcon: 'T8-shezhi-xuanzhong',
      },
      {
        key: 'setting',
        url: '/setting/index',
        name: '质控数据查询',
        icon: 'T8-shezhi-weixuanzhong',
        selIcon: 'T8-shezhi-xuanzhong',
      },
      {
        key: 'setting',
        url: '/setting/index',
        name: '质控修改记录查询',
        icon: 'T8-shezhi-weixuanzhong',
        selIcon: 'T8-shezhi-xuanzhong',
      },
      {
        key: 'setting',
        url: '/setting/index',
        name: '失控数据查询/失控报告',
        icon: 'T8-shezhi-weixuanzhong',
        selIcon: 'T8-shezhi-xuanzhong',
      },
      {
        key: 'setting',
        url: '/setting/index',
        name: '质控分析(Westguard图)',
        icon: 'T8-shezhi-weixuanzhong',
        selIcon: 'T8-shezhi-xuanzhong',
      },
      {
        key: 'setting',
        url: '/setting/index',
        name: '质控分析(Grubbs图)',
        icon: 'T8-shezhi-weixuanzhong',
        selIcon: 'T8-shezhi-xuanzhong',
      },
      {
        key: 'setting',
        url: '/setting/index',
        name: '质控分析(优盾图)',
        icon: 'T8-shezhi-weixuanzhong',
        selIcon: 'T8-shezhi-xuanzhong',
      },
      {
        key: 'setting',
        url: '/setting/index',
        name: '质控月汇总表',
        icon: 'T8-shezhi-weixuanzhong',
        selIcon: 'T8-shezhi-xuanzhong',
      },
      {
        key: 'setting',
        url: '/setting/index',
        name: '质控期间数据分析',
        icon: 'T8-shezhi-weixuanzhong',
        selIcon: 'T8-shezhi-xuanzhong',
      },
      {
        key: 'setting',
        url: '/setting/index',
        name: '质控CV统计表',
        icon: 'T8-shezhi-weixuanzhong',
        selIcon: 'T8-shezhi-xuanzhong',
      },
      {
        key: 'setting',
        url: '/setting/index',
        name: '质控CV趋势变化图',
        icon: 'T8-shezhi-weixuanzhong',
        selIcon: 'T8-shezhi-xuanzhong',
      },
      {
        key: 'setting',
        url: '/setting/index',
        name: '质控CV不合格率',
        icon: 'T8-shezhi-weixuanzhong',
        selIcon: 'T8-shezhi-xuanzhong',
      },
      {
        key: 'setting',
        url: '/setting/index',
        name: '质控月统计表',
        icon: 'T8-shezhi-weixuanzhong',
        selIcon: 'T8-shezhi-xuanzhong',
      },
      {
        key: 'setting',
        url: '/setting/index',
        name: '室内质控开展率',
        icon: 'T8-shezhi-weixuanzhong',
        selIcon: 'T8-shezhi-xuanzhong',
      },
      {
        key: 'setting',
        url: '/setting/index',
        name: '数据上报卫生部临检中心',
        icon: 'T8-shezhi-weixuanzhong',
        selIcon: 'T8-shezhi-xuanzhong',
      },
      {
        key: 'setting',
        url: '/setting/index',
        name: '个体化用药室内质控',
        icon: 'T8-shezhi-weixuanzhong',
        selIcon: 'T8-shezhi-xuanzhong',
      },
      {
        key: 'setting',
        url: '/setting/index',
        name: '个体化用药室内质控查询',
        icon: 'T8-shezhi-weixuanzhong',
        selIcon: 'T8-shezhi-xuanzhong',
      },
    ],
  },
  {
    key: 'setting',
    url: '/setting/index',
    name: '统计分析',
    icon: 'T8-shezhi-weixuanzhong',
    selIcon: 'T8-shezhi-xuanzhong',
    children: [
      {
        key: 'setting',
        url: '/setting/index',
        name: '标本流转TAT统计',
        icon: 'T8-shezhi-weixuanzhong',
        selIcon: 'T8-shezhi-xuanzhong',
      },
      {
        key: 'setting',
        url: '/setting/index',
        name: '质量指标统计',
        icon: 'T8-shezhi-weixuanzhong',
        selIcon: 'T8-shezhi-xuanzhong',
      },
      {
        key: 'setting',
        url: '/setting/index',
        name: '工作量统计表',
        icon: 'T8-shezhi-weixuanzhong',
        selIcon: 'T8-shezhi-xuanzhong',
      },
      {
        key: 'setting',
        url: '/setting/index',
        name: '危急值上报表',
        icon: 'T8-shezhi-weixuanzhong',
        selIcon: 'T8-shezhi-xuanzhong',
      },
      {
        key: 'setting',
        url: '/setting/index',
        name: '项目阳性率统计表',
        icon: 'T8-shezhi-weixuanzhong',
        selIcon: 'T8-shezhi-xuanzhong',
      },
      {
        key: 'setting',
        url: '/setting/index',
        name: '普件结果统计表',
        icon: 'T8-shezhi-weixuanzhong',
        selIcon: 'T8-shezhi-xuanzhong',
      },
      {
        key: 'setting',
        url: '/setting/index',
        name: '特检结果统计表',
        icon: 'T8-shezhi-weixuanzhong',
        selIcon: 'T8-shezhi-xuanzhong',
      },
      {
        key: 'setting',
        url: '/setting/index',
        name: '报告打印记录表',
        icon: 'T8-shezhi-weixuanzhong',
        selIcon: 'T8-shezhi-xuanzhong',
      },
      {
        key: 'setting',
        url: '/setting/index',
        name: '检验项目总汇表',
        icon: 'T8-shezhi-weixuanzhong',
        selIcon: 'T8-shezhi-xuanzhong',
      },
      {
        key: 'setting',
        url: '/setting/index',
        name: '模式组合报表',
        icon: 'T8-shezhi-weixuanzhong',
        selIcon: 'T8-shezhi-xuanzhong',
      },
      {
        key: 'setting',
        url: '/setting/index',
        name: '检验结果趋势分析',
        icon: 'T8-shezhi-weixuanzhong',
        selIcon: 'T8-shezhi-xuanzhong',
      },
      {
        key: 'setting',
        url: '/setting/index',
        name: '检验结果比较分析',
        icon: 'T8-shezhi-weixuanzhong',
        selIcon: 'T8-shezhi-xuanzhong',
      },
      {
        key: 'setting',
        url: '/setting/index',
        name: '检验结果超限分析',
        icon: 'T8-shezhi-weixuanzhong',
        selIcon: 'T8-shezhi-xuanzhong',
      },
      {
        key: 'setting',
        url: '/setting/index',
        name: '项目结果变化率分析',
        icon: 'T8-shezhi-weixuanzhong',
        selIcon: 'T8-shezhi-xuanzhong',
      },
      {
        key: 'setting',
        url: '/setting/index',
        name: '项目结果浮动均值',
        icon: 'T8-shezhi-weixuanzhong',
        selIcon: 'T8-shezhi-xuanzhong',
      },
      {
        key: 'setting',
        url: '/setting/index',
        name: '项目结合学术统计',
        icon: 'T8-shezhi-weixuanzhong',
        selIcon: 'T8-shezhi-xuanzhong',
      },
      {
        key: 'setting',
        url: '/setting/index',
        name: '项目结果动态均值',
        icon: 'T8-shezhi-weixuanzhong',
        selIcon: 'T8-shezhi-xuanzhong',
      },
      {
        key: 'setting',
        url: '/setting/index',
        name: '项目结果正太分析',
        icon: 'T8-shezhi-weixuanzhong',
        selIcon: 'T8-shezhi-xuanzhong',
      },
      {
        key: 'setting',
        url: '/setting/index',
        name: '项目结果ROC曲线',
        icon: 'T8-shezhi-weixuanzhong',
        selIcon: 'T8-shezhi-xuanzhong',
      },
      {
        key: 'setting',
        url: '/setting/index',
        name: '项目结果线性回归分析',
        icon: 'T8-shezhi-weixuanzhong',
        selIcon: 'T8-shezhi-xuanzhong',
      },
    ],
  },
  {
    key: 'setting',
    url: '/setting/index',
    name: '溯源查询',
    icon: 'T8-shezhi-weixuanzhong',
    selIcon: 'T8-shezhi-xuanzhong',
    children: [
      {
        key: 'setting',
        url: '/setting/index',
        name: '申请单修改日志查询',
        icon: 'T8-shezhi-weixuanzhong',
        selIcon: 'T8-shezhi-xuanzhong',
      },
      {
        key: 'setting',
        url: '/setting/index',
        name: '报告单修改日志查询',
        icon: 'T8-shezhi-weixuanzhong',
        selIcon: 'T8-shezhi-xuanzhong',
      },
      {
        key: 'setting',
        url: '/setting/index',
        name: '报告单打印日志查询',
        icon: 'T8-shezhi-weixuanzhong',
        selIcon: 'T8-shezhi-xuanzhong',
      },
      {
        key: 'setting',
        url: '/setting/index',
        name: '质控修改日志查询',
        icon: 'T8-shezhi-weixuanzhong',
        selIcon: 'T8-shezhi-xuanzhong',
      },
      {
        key: 'setting',
        url: '/setting/index',
        name: '实验原始结果查询',
        icon: 'T8-shezhi-weixuanzhong',
        selIcon: 'T8-shezhi-xuanzhong',
      },
      {
        key: 'setting',
        url: '/setting/index',
        name: '样本流转日志查询',
        icon: 'T8-shezhi-weixuanzhong',
        selIcon: 'T8-shezhi-xuanzhong',
      },
      {
        key: 'setting',
        url: '/setting/index',
        name: '异常操作日志查询',
        icon: 'T8-shezhi-weixuanzhong',
        selIcon: 'T8-shezhi-xuanzhong',
      },
      {
        key: 'setting',
        url: '/setting/index',
        name: '系统使用日志查询',
        icon: 'T8-shezhi-weixuanzhong',
        selIcon: 'T8-shezhi-xuanzhong',
      },
    ],
  },
  {
    key: 'setting',
    url: '/setting/index',
    name: '样本库管理',
    icon: 'T8-shezhi-weixuanzhong',
    selIcon: 'T8-shezhi-xuanzhong',
    children: [
      {
        key: 'setting',
        url: '',
        name: '标本入库',
        icon: 'T8-shezhi-weixuanzhong',
        selIcon: 'T8-shezhi-xuanzhong',
        children: [],
      },
      {
        key: 'setting',
        url: '',
        name: '标本入库',
        icon: 'T8-shezhi-weixuanzhong',
        selIcon: 'T8-shezhi-xuanzhong',
        children: [],
      },
      {
        key: 'setting',
        url: '',
        name: '标本移库',
        icon: 'T8-shezhi-weixuanzhong',
        selIcon: 'T8-shezhi-xuanzhong',
        children: [],
      },
      {
        key: 'setting',
        url: '',
        name: '库位查询',
        icon: 'T8-shezhi-weixuanzhong',
        selIcon: 'T8-shezhi-xuanzhong',
        children: [],
      },
      {
        key: 'setting',
        url: '',
        name: '库位统计',
        icon: 'T8-shezhi-weixuanzhong',
        selIcon: 'T8-shezhi-xuanzhong',
        children: [],
      },
      {
        key: 'setting',
        url: '',
        name: '库位清理',
        icon: 'T8-shezhi-weixuanzhong',
        selIcon: 'T8-shezhi-xuanzhong',
        children: [],
      },
      {
        key: 'setting',
        url: '',
        name: '库位设置',
        icon: 'T8-shezhi-weixuanzhong',
        selIcon: 'T8-shezhi-xuanzhong',
        children: [
          {
            key: 'setting',
            url: '',
            name: '样本管架设置',
            icon: 'T8-shezhi-weixuanzhong',
            selIcon: 'T8-shezhi-xuanzhong',
          },
          {
            key: 'setting',
            url: '',
            name: '样本库位结构设置',
            icon: 'T8-shezhi-weixuanzhong',
            selIcon: 'T8-shezhi-xuanzhong',
          },
        ],
      },
    ],
  },
  {
    key: 'commonMaterials',
    url: '/commonMaterials/index',
    name: '基础数据设置',
    icon: 'T8-shezhi-weixuanzhong',
    selIcon: 'T8-shezhi-xuanzhong',
    children: [
      {
        key: 'inspectionInstruments',
        url: '/commonMaterials/inspectionInstruments',
        name: '检验仪器维护',
        icon: 'T8-shezhi-weixuanzhong',
        selIcon: 'T8-shezhi-xuanzhong',
        btn: [
          {
            key: 'add',
            url: '',
            name: '新增',
            icon: 'T8-shezhi-weixuanzhong',
            selIcon: 'T8-shezhi-xuanzhong',
            children: [],
          },
          {
            key: 'edit',
            url: '',
            name: '编辑',
            icon: 'T8-shezhi-weixuanzhong',
            selIcon: 'T8-shezhi-xuanzhong',
            children: [],
          },
          {
            key: 'delete',
            url: '',
            name: '删除',
            icon: 'T8-shezhi-weixuanzhong',
            selIcon: 'T8-shezhi-xuanzhong',
            children: [],
          },
          {
            key: 'import',
            url: '',
            name: '导入',
            icon: 'T8-shezhi-weixuanzhong',
            selIcon: 'T8-shezhi-xuanzhong',
            children: [],
          },
          {
            key: 'export',
            url: '',
            name: '导出',
            icon: 'T8-shezhi-weixuanzhong',
            selIcon: 'T8-shezhi-xuanzhong',
            children: [],
          },
          {
            key: 'bind',
            url: '',
            name: '绑定',
            icon: 'T8-shezhi-weixuanzhong',
            selIcon: 'T8-shezhi-xuanzhong',
            children: [],
          },
          {
            key: 'printAdd',
            url: '',
            name: '打印新增',
            icon: 'T8-shezhi-weixuanzhong',
            selIcon: 'T8-shezhi-xuanzhong',
            children: [],
          },
          {
            key: 'printEdit',
            url: '',
            name: '打印编辑',
            icon: 'T8-shezhi-weixuanzhong',
            selIcon: 'T8-shezhi-xuanzhong',
            children: [],
          },
          {
            key: 'printDelete',
            url: '',
            name: '打印删除',
            icon: 'T8-shezhi-weixuanzhong',
            selIcon: 'T8-shezhi-xuanzhong',
            children: [],
          },
        ],
      },
      {
        url: '/commonMaterials/instrProjectMaintenance',
        name: '仪器项目维护',
      },
      {
        key: 'basicData',
        url: '/commonMaterials/basicData',
        name: '常见资料维护',
        icon: 'T8-shezhi-weixuanzhong',
        selIcon: 'T8-shezhi-xuanzhong',
        children: [],
        btn: [
          {
            key: 'add',
            url: '',
            name: '新增',
            icon: 'T8-shezhi-weixuanzhong',
            selIcon: 'T8-shezhi-xuanzhong',
            children: [],
          },
          {
            key: 'edit',
            url: '',
            name: '编辑',
            icon: 'T8-shezhi-weixuanzhong',
            selIcon: 'T8-shezhi-xuanzhong',
            children: [],
          },
          {
            key: 'delete',
            url: '',
            name: '删除',
            icon: 'T8-shezhi-weixuanzhong',
            selIcon: '8-shezhi-xuanzhong',
            children: [],
          },
          {
            key: 'import',
            url: '',
            name: '导入',
            icon: 'T8-shezhi-weixuanzhong',
            selIcon: 'T8-shezhi-xuanzhong',
            children: [],
          },
          {
            key: 'export',
            url: '',
            name: '导出',
            icon: 'T8-shezhi-weixuanzhong',
            selIcon: 'T8-shezhi-xuanzhong',
            children: [],
          },
        ],
      },

      {
        key: 'majorGroup',
        url: '/commonMaterials/majorGroup',
        name: '专业分类维护',
        icon: 'T8-shezhi-weixuanzhong',
        selIcon: 'T8-shezhi-xuanzhong',
        children: [],
        btn: [
          {
            key: 'add',
            url: '',
            name: '新增',
            icon: 'T8-shezhi-weixuanzhong',
            selIcon: 'T8-shezhi-xuanzhong',
            children: [],
          },
          {
            key: 'edit',
            url: '',
            name: '编辑',
            icon: 'T8-shezhi-weixuanzhong',
            selIcon: 'T8-shezhi-xuanzhong',
            children: [],
          },
          {
            key: 'delete',
            url: '',
            name: '删除',
            icon: 'T8-shezhi-weixuanzhong',
            selIcon: 'T8-shezhi-xuanzhong',
            children: [],
          },
          {
            key: 'import',
            url: '',
            name: '导入',
            icon: 'T8-shezhi-weixuanzhong',
            selIcon: 'T8-shezhi-xuanzhong',
            children: [],
          },
          {
            key: 'export',
            url: '',
            name: '导出',
            icon: 'T8-shezhi-weixuanzhong',
            selIcon: 'T8-shezhi-xuanzhong',
            children: [],
          },
          {
            key: 'bind',
            url: '',
            name: '绑定',
            icon: 'T8-shezhi-weixuanzhong',
            selIcon: 'T8-shezhi-xuanzhong',
            children: [],
          },
        ],
      },
      {
        key: 'taskGroup',
        url: '/commonMaterials/taskGroup',
        name: '任务分类维护',
        icon: 'T8-shezhi-weixuanzhong',
        selIcon: 'T8-shezhi-xuanzhong',
        children: [],
        btn: [
          {
            key: 'bind',
            url: '',
            name: '绑定',
            icon: 'T8-shezhi-weixuanzhong',
            selIcon: 'T8-shezhi-xuanzhong',
            children: [],
          },
        ],
      },
      {
        key: 'manageGroup',
        url: '/commonMaterials/manageGroup',
        name: '管理分类维护',
        icon: 'T8-shezhi-weixuanzhong',
        selIcon: 'T8-shezhi-xuanzhong',
        children: [],
        btn: [
          {
            key: 'add',
            url: '',
            name: '新增',
            icon: 'T8-shezhi-weixuanzhong',
            selIcon: 'T8-shezhi-xuanzhong',
            children: [],
          },
          {
            key: 'edit',
            url: '',
            name: '编辑',
            icon: 'T8-shezhi-weixuanzhong',
            selIcon: 'T8-shezhi-xuanzhong',
            children: [],
          },
          {
            key: 'delete',
            url: '',
            name: '删除',
            icon: 'T8-shezhi-weixuanzhong',
            selIcon: 'T8-shezhi-xuanzhong',
            children: [],
          },
          {
            key: 'import',
            url: '',
            name: '导入',
            icon: 'T8-shezhi-weixuanzhong',
            selIcon: 'T8-shezhi-xuanzhong',
            children: [],
          },
          {
            key: 'export',
            url: '',
            name: '导出',
            icon: 'T8-shezhi-weixuanzhong',
            selIcon: 'T8-shezhi-xuanzhong',
            children: [],
          },
        ],
      },
      {
        key: 'reportingUnit',
        name: '报告单元及相关对照',
        url: '/commonMaterials/reportingUnit',
        icon: 'T8-shezhi-weixuanzhong',
        selIcon: 'T8-shezhi-xuanzhong',
        children: [],
      },
      {
        key: 'applyProjectGroup',
        url: '/commonMaterials/applyProjectGroup',
        name: '申请项目维护',
        icon: 'T8-shezhi-weixuanzhong',
        selIcon: 'T8-shezhi-xuanzhong',
        children: [],
        btn: [
          {
            key: 'add',
            url: '',
            name: '新增',
            icon: 'T8-shezhi-weixuanzhong',
            selIcon: 'T8-shezhi-xuanzhong',
            children: [],
          },
          {
            key: 'edit',
            url: '',
            name: '编辑',
            icon: 'T8-shezhi-weixuanzhong',
            selIcon: 'T8-shezhi-xuanzhong',
            children: [],
          },
          {
            key: 'delete',
            url: '',
            name: '删除',
            icon: 'T8-shezhi-weixuanzhong',
            selIcon: 'T8-shezhi-xuanzhong',
            children: [],
          },
          {
            key: 'import',
            url: '',
            name: '导入',
            icon: 'T8-shezhi-weixuanzhong',
            selIcon: 'T8-shezhi-xuanzhong',
            children: [],
          },
          {
            key: 'export',
            url: '',
            name: '导出',
            icon: 'T8-shezhi-weixuanzhong',
            selIcon: 'T8-shezhi-xuanzhong',
            children: [],
          },

          {
            key: 'usingHospitalsAdd',
            url: '',
            name: '使用医院新增',
            icon: 'T8-shezhi-weixuanzhong',
            selIcon: 'T8-shezhi-xuanzhong',
            children: [],
          },
          {
            key: 'usingHospitalsDelete',
            url: '',
            name: '使用医院删除',
            icon: 'T8-shezhi-weixuanzhong',
            selIcon: 'T8-shezhi-xuanzhong',
            children: [],
          },

          {
            key: 'combinationDetailsAdd',
            url: '',
            name: '组合明细新增',
            icon: 'T8-shezhi-weixuanzhong',
            selIcon: 'T8-shezhi-xuanzhong',
            children: [],
          },
          {
            key: 'combinationDetailsDelete',
            url: '',
            name: '组合明细删除',
            icon: 'T8-shezhi-weixuanzhong',
            selIcon: 'T8-shezhi-xuanzhong',
            children: [],
          },

          {
            key: 'instrumentAdd',
            url: '',
            name: '仪器新增',
            icon: 'T8-shezhi-weixuanzhong',
            selIcon: 'T8-shezhi-xuanzhong',
            children: [],
          },
          {
            key: 'instrumentDelete',
            url: '',
            name: '仪器删除',
            icon: 'T8-shezhi-weixuanzhong',
            selIcon: 'T8-shezhi-xuanzhong',
            children: [],
          },

          {
            key: 'reportAdd',
            url: '',
            name: '报告项目新增',
            icon: 'T8-shezhi-weixuanzhong',
            selIcon: 'T8-shezhi-xuanzhong',
            children: [],
          },
          {
            key: 'reportDelete',
            url: '',
            name: '报告项目删除',
            icon: 'T8-shezhi-weixuanzhong',
            selIcon: 'T8-shezhi-xuanzhong',
            children: [],
          },

          {
            key: 'guidePriceAdd',
            url: '',
            name: '基准价格新增',
            icon: 'T8-shezhi-weixuanzhong',
            selIcon: 'T8-shezhi-xuanzhong',
            children: [],
          },
          {
            key: 'guidePriceDelete',
            url: '',
            name: '基准价格删除',
            icon: 'T8-shezhi-weixuanzhong',
            selIcon: 'T8-shezhi-xuanzhong',
            children: [],
          },
          {
            key: 'guidePriceEdit',
            url: '',
            name: '基准价格编辑',
            icon: 'T8-shezhi-weixuanzhong',
            selIcon: 'T8-shezhi-xuanzhong',
            children: [],
          },
        ],
      },
      {
        key: 'applyReportPC',
        url: '/commonMaterials/applyReportPC',
        name: '报告项目维护',
        icon: 'T8-shezhi-weixuanzhong',
        selIcon: 'T8-shezhi-xuanzhong',
        children: [],
        btn: [
          {
            key: 'add',
            url: '',
            name: '新增',
            icon: 'T8-shezhi-weixuanzhong',
            selIcon: 'T8-shezhi-xuanzhong',
            children: [],
          },
          {
            key: 'edit',
            url: '',
            name: '编辑',
            icon: 'T8-shezhi-weixuanzhong',
            selIcon: 'T8-shezhi-xuanzhong',
            children: [],
          },
          {
            key: 'delete',
            url: '',
            name: '删除',
            icon: 'T8-shezhi-weixuanzhong',
            selIcon: 'T8-shezhi-xuanzhong',
            children: [],
          },
          {
            key: 'import',
            url: '',
            name: '导入',
            icon: 'T8-shezhi-weixuanzhong',
            selIcon: 'T8-shezhi-xuanzhong',
            children: [],
          },
          {
            key: 'export',
            url: '',
            name: '导出',
            icon: 'T8-shezhi-weixuanzhong',
            selIcon: 'T8-shezhi-xuanzhong',
            children: [],
          },
          {
            key: 'instrumentNumberAdd',
            url: '',
            name: '仪器号新增',
            icon: 'T8-shezhi-weixuanzhong',
            selIcon: 'T8-shezhi-xuanzhong',
            children: [],
          },
          {
            key: 'instrumentNumberDelete',
            url: '',
            name: '仪器号删除',
            icon: 'T8-shezhi-weixuanzhong',
            selIcon: 'T8-shezhi-xuanzhong',
            children: [],
          },
          {
            key: 'instrumentNumberEdit',
            url: '',
            name: '仪器号编辑',
            icon: 'T8-shezhi-weixuanzhong',
            selIcon: 'T8-shezhi-xuanzhong',
            children: [],
          },

          {
            key: 'referenceValueAdd',
            url: '',
            name: '参考值新增',
            icon: 'T8-shezhi-weixuanzhong',
            selIcon: 'T8-shezhi-xuanzhong',
            children: [],
          },
          {
            key: 'referenceValueDelete',
            url: '',
            name: '参考值删除',
            icon: 'T8-shezhi-weixuanzhong',
            selIcon: 'T8-shezhi-xuanzhong',
            children: [],
          },
          {
            key: 'referenceValueEdit',
            url: '',
            name: '参考值编辑',
            icon: 'T8-shezhi-weixuanzhong',
            selIcon: 'T8-shezhi-xuanzhong',
            children: [],
          },

          {
            key: 'criticalValueAdd',
            url: '',
            name: '危机值新增',
            icon: 'T8-shezhi-weixuanzhong',
            selIcon: '8-shezhi-xuanzhong',
            children: [],
          },
          {
            key: 'criticalValueDelete',
            url: '',
            name: '危机值删除',
            icon: 'T8-shezhi-weixuanzhong',
            selIcon: 'T8-shezhi-xuanzhong',
            children: [],
          },
          {
            key: 'criticalValueEdit',
            url: '',
            name: '危机值编辑',
            icon: 'T8-shezhi-weixuanzhong',
            selIcon: 'T8-shezhi-xuanzhong',
            children: [],
          },

          {
            key: 'formulaAdd',
            url: '',
            name: '计算公司新增',
            icon: 'T8-shezhi-weixuanzhong',
            selIcon: 'T8-shezhi-xuanzhong',
            children: [],
          },
          {
            key: 'formulaDelete',
            url: '',
            name: '计算公司删除',
            icon: 'T8-shezhi-weixuanzhong',
            selIcon: 'T8-shezhi-xuanzhong',
            children: [],
          },
          {
            key: 'formulaEdit',
            url: '',
            name: '计算公司编辑',
            icon: 'T8-shezhi-weixuanzhong',
            selIcon: 'T8-shezhi-xuanzhong',
            children: [],
          },

          {
            key: 'commonResultsAdd',
            url: '',
            name: '常用结果新增',
            icon: 'T8-shezhi-weixuanzhong',
            selIcon: 'T8-shezhi-xuanzhong',
            children: [],
          },
          {
            key: 'commonResultsDelete',
            url: '',
            name: '常用结果删除',
            icon: 'T8-shezhi-weixuanzhong',
            selIcon: 'T8-shezhi-xuanzhong',
            children: [],
          },
          {
            key: 'commonResultsEdit',
            url: '',
            name: '常用结果编辑',
            icon: 'T8-shezhi-weixuanzhong',
            selIcon: 'T8-shezhi-xuanzhong',
            children: [],
          },
        ],
      },
      {
        key: 'insUnitDiscount',
        url: '/commonMaterials/insUnitDiscount',
        name: '送检单位项目价格维护',
        icon: 'T8-shezhi-weixuanzhong',
        selIcon: 'T8-shezhi-xuanzhong',
        children: [],
        btn: [
          {
            key: 'add',
            url: '',
            name: '新增',
            icon: 'T8-shezhi-weixuanzhong',
            selIcon: 'T8-shezhi-xuanzhong',
            children: [],
          },
          {
            key: 'edit',
            url: '',
            name: '编辑',
            icon: 'T8-shezhi-weixuanzhong',
            selIcon: 'T8-shezhi-xuanzhong',
            children: [],
          },
          {
            key: 'delete',
            url: '',
            name: '删除',
            icon: 'T8-shezhi-weixuanzhong',
            selIcon: 'T8-shezhi-xuanzhong',
            children: [],
          },
          {
            key: 'import',
            url: '',
            name: '导入',
            icon: 'T8-shezhi-weixuanzhong',
            selIcon: 'T8-shezhi-xuanzhong',
            children: [],
          },
          {
            key: 'export',
            url: '',
            name: '导出',
            icon: 'T8-shezhi-weixuanzhong',
            selIcon: 'T8-shezhi-xuanzhong',
            children: [],
          },
        ],
      },
      {
        key: 'inspectionUnit',
        url: '/commonMaterials/inspectionUnit',
        name: '送检单位维护',
        icon: 'T8-shezhi-weixuanzhong',
        selIcon: 'T8-shezhi-xuanzhong',
        children: [],
        btn: [
          {
            key: 'add',
            url: '',
            name: '新增',
            icon: 'T8-shezhi-weixuanzhong',
            selIcon: 'T8-shezhi-xuanzhong',
            children: [],
          },
          {
            key: 'edit',
            url: '',
            name: '编辑',
            icon: 'T8-shezhi-weixuanzhong',
            selIcon: 'T8-shezhi-xuanzhong',
            children: [],
          },
          {
            key: 'delete',
            url: '',
            name: '删除',
            icon: 'T8-shezhi-weixuanzhong',
            selIcon: 'T8-shezhi-xuanzhong',
            children: [],
          },
          {
            key: 'import',
            url: '',
            name: '导入',
            icon: 'T8-shezhi-weixuanzhong',
            selIcon: 'T8-shezhi-xuanzhong',
            children: [],
          },
          {
            key: 'export',
            url: '',
            name: '导出',
            icon: 'T8-shezhi-weixuanzhong',
            selIcon: 'T8-shezhi-xuanzhong',
            children: [],
          },
        ],
      },
      {
        key: 'insUnitDiscount',
        url: '录入分类维护',
        name: '送检医生维护',
        icon: 'T8-shezhi-weixuanzhong',
        selIcon: 'T8-shezhi-xuanzhong',
        children: [],
      },

      {
        key: 'insUnitDiscount',
        url: '送检区域维护',
        name: '送检区域维护',
        icon: 'T8-shezhi-weixuanzhong',
        selIcon: 'T8-shezhi-xuanzhong',
        children: [],
      },
      {
        key: 'insUnitDiscount',
        url: '代理商维护',
        name: '代理商维护',
        icon: 'T8-shezhi-weixuanzhong',
        selIcon: 'T8-shezhi-xuanzhong',
        children: [],
      },
      {
        key: 'insUnitDiscount',
        url: '送检区域维护',
        name: '代理商与送检单位对照',
        icon: 'T8-shezhi-weixuanzhong',
        selIcon: 'T8-shezhi-xuanzhong',
        children: [],
      },
      {
        key: 'insUnitDiscount',
        url: '送检区域维护',
        name: '检验目的维护',
        icon: 'T8-shezhi-weixuanzhong',
        selIcon: 'T8-shezhi-xuanzhong',
        children: [],
      },
      {
        key: 'entryMaintenance',
        url: '/setting/entryMaintenance',
        name: '常用词条维护',
        icon: 'T8-shezhi-weixuanzhong',
        selIcon: 'T8-shezhi-xuanzhong',
        children: [],
      },
      {
        key: 'insUnitDiscount',
        url: '送检区域维护',
        name: '个性提示维护',
        icon: 'T8-shezhi-weixuanzhong',
        selIcon: 'T8-shezhi-xuanzhong',
        children: [],
      },
      {
        key: 'insUnitDiscount',
        url: '送检区域维护',
        name: '审核规则设置',
        icon: 'T8-shezhi-weixuanzhong',
        selIcon: 'T8-shezhi-xuanzhong',
        children: [],
      },
      {
        key: 'insUnitDiscount',
        url: '送检区域维护',
        name: '诊断规则设置',
        icon: 'T8-shezhi-weixuanzhong',
        selIcon: 'T8-shezhi-xuanzhong',
        children: [],
      },
      {
        key: 'batchInputTemplate',
        url: '/setting/batchInputTemplate',
        name: '批输入方式维护',
        icon: 'T8-shezhi-weixuanzhong',
        selIcon: 'T8-shezhi-xuanzhong',
        children: [],
      },
    ],
  },
  {
    key: 'setting',
    url: '/setting/index',
    name: '系统设置',
    icon: 'T8-shezhi-weixuanzhong',
    selIcon: 'T8-shezhi-xuanzhong',
    children: [
      {
        key: 'roleMange',
        url: '',
        name: '报告模版管理',
        icon: 'T8-shezhi-weixuanzhong',
        selIcon: 'T8-shezhi-xuanzhong',
        children: [
          {
            key: 'roleMange',
            url: '',
            name: '专业组关联报告模版设置',
            icon: 'T8-shezhi-weixuanzhong',
            selIcon: 'T8-shezhi-xuanzhong',
          },
          {
            key: 'roleMange',
            url: '',
            name: '申请项关联报告模版设置',
            icon: 'T8-shezhi-weixuanzhong',
            selIcon: 'T8-shezhi-xuanzhong',
          },
          {
            key: 'roleMange',
            url: '',
            name: '送检单位关联报告模版设置',
            icon: 'T8-shezhi-weixuanzhong',
            selIcon: 'T8-shezhi-xuanzhong',
          },
        ],
      },
      {
        key: 'roleMange',
        url: '/setting/applicationFormModel',
        name: '专业组关联选项设置',
        icon: 'T8-shezhi-weixuanzhong',
        selIcon: 'T8-shezhi-xuanzhong',
        children: [],
      },
      {
        key: 'globalOptionsSet',
        url: '/setting/globalOptionsSet',
        name: '系统全局选项设置',
        icon: 'T8-shezhi-weixuanzhong',
        selIcon: 'T8-shezhi-xuanzhong',
        children: [],
        btn: [
          {
            key: 'add',
            url: '',
            name: '新增',
            icon: 'T8-shezhi-weixuanzhong',
            selIcon: 'T8-shezhi-xuanzhong',
            children: [],
          },
          {
            key: 'edit',
            url: '',
            name: '编辑',
            icon: 'T8-shezhi-weixuanzhong',
            selIcon: 'T8-shezhi-xuanzhong',
            children: [],
          },
          {
            key: 'delete',
            url: '',
            name: '删除',
            icon: 'T8-shezhi-weixuanzhong',
            selIcon: 'T8-shezhi-xuanzhong',
            children: [],
          },
          {
            key: 'import',
            url: '',
            name: '导入',
            icon: 'T8-shezhi-weixuanzhong',
            selIcon: 'T8-shezhi-xuanzhong',
            children: [],
          },
          {
            key: 'export',
            url: '',
            name: '导出',
            icon: 'T8-shezhi-weixuanzhong',
            selIcon: 'T8-shezhi-xuanzhong',
            children: [],
          },
        ],
      },

      {
        key: 'roleMange',
        url: '用户及权限设置',
        name: '用户及权限设置',
        icon: 'T8-shezhi-weixuanzhong',
        selIcon: 'T8-shezhi-xuanzhong',
        children: [
          {
            key: 'roleMange',
            url: '/setting/roleMange',
            name: '用户设置',
            icon: 'T8-shezhi-weixuanzhong',
            selIcon: 'T8-shezhi-xuanzhong',
            children: [],
            btn: [
              {
                key: 'add',
                url: '',
                name: '新增',
                icon: 'T8-shezhi-weixuanzhong',
                selIcon: 'T8-shezhi-xuanzhong',
                children: [],
              },
              {
                key: 'edit',
                url: '',
                name: '编辑',
                icon: 'T8-shezhi-weixuanzhong',
                selIcon: 'T8-shezhi-xuanzhong',
                children: [],
              },
              {
                key: 'delete',
                url: '',
                name: '删除',
                icon: 'T8-shezhi-weixuanzhong',
                selIcon: 'T8-shezhi-xuanzhong',
                children: [],
              },
              {
                key: 'import',
                url: '',
                name: '导入',
                icon: 'T8-shezhi-weixuanzhong',
                selIcon: 'T8-shezhi-xuanzhong',
                children: [],
              },
              {
                key: 'export',
                url: '',
                name: '导出',
                icon: 'T8-shezhi-weixuanzhong',
                selIcon: 'T8-shezhi-xuanzhong',
                children: [],
              },
            ],
          },
          {
            key: 'permissionMange',
            url: '/setting/permissionMange',
            name: '权限设置',
            icon: 'T8-shezhi-weixuanzhong',
            selIcon: 'T8-shezhi-xuanzhong',
            children: [],
            btn: [
              {
                key: 'add',
                url: '',
                name: '新增',
                icon: 'T8-shezhi-weixuanzhong',
                selIcon: 'T8-shezhi-xuanzhong',
                children: [],
              },
              {
                key: 'edit',
                url: '',
                name: '编辑',
                icon: 'T8-shezhi-weixuanzhong',
                selIcon: 'T8-shezhi-xuanzhong',
                children: [],
              },
              {
                key: 'delete',
                url: '',
                name: '删除',
                icon: 'T8-shezhi-weixuanzhong',
                selIcon: 'T8-shezhi-xuanzhong',
                children: [],
              },
              {
                key: 'import',
                url: '',
                name: '导入',
                icon: 'T8-shezhi-weixuanzhong',
                selIcon: 'T8-shezhi-xuanzhong',
                children: [],
              },
              {
                key: 'export',
                url: '',
                name: '导出',
                icon: 'T8-shezhi-weixuanzhong',
                selIcon: 'T8-shezhi-xuanzhong',
                children: [],
              },
            ],
          },
          {
            key: 'organize',
            url: '/setting/organize',
            name: '角色管理',
            icon: 'T8-shezhi-weixuanzhong',
            selIcon: 'T8-shezhi-xuanzhong',
            children: [],
            btn: [
              {
                key: 'add',
                url: '',
                name: '新增',
                icon: 'T8-shezhi-weixuanzhong',
                selIcon: 'T8-shezhi-xuanzhong',
                children: [],
              },
              {
                key: 'edit',
                url: '',
                name: '编辑',
                icon: 'T8-shezhi-weixuanzhong',
                selIcon: 'T8-shezhi-xuanzhong',
                children: [],
              },
              {
                key: 'delete',
                url: '',
                name: '删除',
                icon: 'T8-shezhi-weixuanzhong',
                selIcon: 'T8-shezhi-xuanzhong',
                children: [],
              },
              {
                key: 'import',
                url: '',
                name: '导入',
                icon: 'T8-shezhi-weixuanzhong',
                selIcon: 'T8-shezhi-xuanzhong',
                children: [],
              },
              {
                key: 'export',
                url: '',
                name: '导出',
                icon: 'T8-shezhi-weixuanzhong',
                selIcon: 'T8-shezhi-xuanzhong',
                children: [],
              },
            ],
          },
        ],
      },
      {
        key: 'roleMange',
        url: '',
        name: '接口参数设置',
        icon: 'T8-shezhi-weixuanzhong',
        selIcon: 'T8-shezhi-xuanzhong',
        children: [
          {
            key: 'roleMange',
            url: '',
            name: '通信参数设置',
            icon: 'T8-shezhi-weixuanzhong',
            selIcon: 'T8-shezhi-xuanzhong',
          },
          {
            key: 'roleMange',
            url: '',
            name: '解码参数设置',
            icon: 'T8-shezhi-weixuanzhong',
            selIcon: 'T8-shezhi-xuanzhong',
          },
          {
            key: 'roleMange',
            url: '',
            name: '结果解析调整设置',
            icon: 'T8-shezhi-weixuanzhong',
            selIcon: 'T8-shezhi-xuanzhong',
          },
        ],
      },
      {
        key: 'roleMange',
        url: '',
        name: '其他参数设置',
        icon: 'T8-shezhi-weixuanzhong',
        selIcon: 'T8-shezhi-xuanzhong',
        children: [
          {
            key: 'roleMange',
            url: '',
            name: '颜色策略设置',
            icon: 'T8-shezhi-weixuanzhong',
            selIcon: 'T8-shezhi-xuanzhong',
          },
        ],
      },

      {
        key: 'roleMange',
        url: '',
        name: '页面格式自定义',
        icon: 'T8-shezhi-weixuanzhong',
        selIcon: 'T8-shezhi-xuanzhong',
        children: [
          {
            key: 'roleMange',
            url: '/setting/applicationFormModel',
            name: '申请单录入格式自定义',
            icon: 'T8-shezhi-weixuanzhong',
            selIcon: 'T8-shezhi-xuanzhong',
            children: [],
          },
          {
            key: 'roleMange',
            url: '/setting/geneInsRepModel',
            name: '普检样本信息格式自定义',
            icon: 'T8-shezhi-weixuanzhong',
            selIcon: 'T8-shezhi-xuanzhong',
            children: [],
          },
          {
            key: 'roleMange',
            url: '/setting/geneInsRepDetailModel',
            name: '普检报告项目列表自定义',
            icon: 'T8-shezhi-weixuanzhong',
            selIcon: 'T8-shezhi-xuanzhong',
            children: [],
          },
          {
            key: 'roleMange',
            url: '/setting/geneInsRepListModel',
            name: '普检报告列表自定义',
            icon: 'T8-shezhi-weixuanzhong',
            selIcon: 'T8-shezhi-xuanzhong',
            children: [],
          },
          {
            key: 'roleMange',
            url: '/setting/reportTemplateModel',
            name: '报告模版模块管理',
            icon: 'T8-shezhi-weixuanzhong',
            selIcon: 'T8-shezhi-xuanzhong',
            children: [],
          },
        ],
      },
      {
        key: 'roleMange',
        url: '',
        name: '流程设置管理',
        icon: 'T8-shezhi-weixuanzhong',
        selIcon: 'T8-shezhi-xuanzhong',
        children: [
          {
            key: 'roleMange',
            url: '/setting/processMange',
            name: '流程自定义管理',
            icon: 'T8-shezhi-weixuanzhong',
            selIcon: 'T8-shezhi-xuanzhong',
            children: [],
          },
          {
            key: 'roleMange',
            url: '/setting/processClassification',
            name: '适用流程对照设置',
            icon: 'T8-shezhi-weixuanzhong',
            selIcon: 'T8-shezhi-xuanzhong',
            children: [],
          },
        ],
      },
      {
        key: 'department',
        url: '/setting/department',
        name: '部门管理',
        icon: 'T8-shezhi-weixuanzhong',
        selIcon: 'T8-shezhi-xuanzhong',
      },
    ],
  },
];
const NAME = { label: '姓名', value: 'patientName', weight: 1, type: 1 };
const SEX = { label: '性别', value: 'sex', weight: 6, type: 3 };
const RECEIVE_BARCODE = { label: '收样条码', value: 'receiveBarcode', weight: 6, type: 1 };
const HOSPITAl_ID = { label: '送检单位', value: 'hospitalId', weight: 6, type: 3 };
const nation = { label: '民族', value: 'nation', weight: 6, type: 3 };
const age = { label: '年龄', value: 'age', weight: 6, type: 1 };
const ageUnit = { label: '年龄单位', value: 'ageUnit', weight: 6, type: 3 };
const idCardNo = { label: '身份证号', value: 'idCardNo', weight: 6, type: 1 };
const telphoneNo = { label: '电话号码', value: 'telphoneNo', weight: 6, type: 1 };
const sendDeptId = { label: '送检科室', value: 'sendDeptId', weight: 6, type: 3 };
const sendDoctorId = { label: '送检医生', value: 'sendDoctorId', weight: 6, type: 3 };
const source = { label: '样本来源', value: 'source', weight: 6, type: 3 };
const bedNo = { label: '床号', value: 'bedNo', weight: 6, type: 1 };
const diagnosis = { label: '临床诊断', value: 'diagnosis', weight: 6, type: 1 };
const createBy = { label: '创建人员', value: 'createBy', weight: 6, type: 1 };
const birthdate = { label: '出生日期', value: 'birthdate', weight: 6, type: 4 };
const collectDate = { label: '采样日期', value: 'collectDate', weight: 6, type: 4 };
const applyDate = { label: '申请日期', value: 'applyDate', weight: 6, type: 4 };
const receiveDate = { label: '物流接收日期', value: 'receiveDate', weight: 6, type: 4 };
const preReceiveDate = { label: '前处理接收时间', value: 'preReceiveDate', weight: 6, type: 4 };
const createDate = { label: '登记日期', value: 'createDate', weight: 6, type: 4 };
// 样本登记-列表搜索自定义
export const EXPORT_OPTIONS_FOR_SEARCH = [
  NAME,
  SEX,
  RECEIVE_BARCODE,
  HOSPITAl_ID,
  nation,
  age,
  ageUnit,
  idCardNo,
  telphoneNo,
  sendDeptId,
  sendDoctorId,
  source,
  bedNo,
  diagnosis,
  createBy,
  birthdate,
  collectDate,
  applyDate,
  receiveDate,
  preReceiveDate,
  createDate,
];
//申请单查询-列表搜索自定义
const hospitalCodeNum = { label: '医院条码号', value: 'hospitalBarcode', type: 1 };
const patientID = { label: '病人ID', value: 'patientId', type: 1 };
const patientNo = { label: '门诊/住院号', value: 'patientNo', type: 1 };
const patientType = { label: '病人类型', value: 'source', type: 3 };
const enName = { label: '英文名', value: 'enName', type: 1 };
const sampleTypeName = { label: '样本类型', value: 'sampleTypeName', type: 3 };
const saleManId = { label: '销售员', value: 'saleManId', type: 1 };
const agentName = { label: '代理商', value: 'agentName', type: 1 };
const isPaymentReceived = { label: '收费标记', value: 'isPaymentReceived', type: 3 };
const payMode = { label: '支付类别', value: 'payMode', type: 3 };
const paymentOrderNo = { label: '付款单号', value: 'paymentOrderNo', type: 1 };
const transportBy = { label: '运送人', value: 'transportBy', type: 1 };
const creatEr = { label: '登记人', value: 'creatEr', type: 1 };
const passportNo = { label: '护照号', value: 'passportNo', type: 1 };
const nationality = { label: '国籍', value: 'nationality', type: 1 };
const remark = { label: '备注', value: 'remark', type: 1 };
const address = { label: '地址', value: 'address', type: 1 };
const sampleBarcode = { label: '样本条码', value: 'sampleBarcode', type: 1 };
const sampleNo = { label: '样本编号', value: 'sampleNo', type: 1 };
const currentNode = { label: '检测状态', value: 'currentNode', type: 3 };
const isEmer = { label: '急诊标记', value: 'isEmer', type: 3 };
const reportDelayFlag = { label: '延迟标记', value: 'reportDelayFlag', type: 3 };
const bloodFlag = { label: '分血标记', value: 'bloodFlag', type: 3 };
const giveUpCheckFlag = { label: '弃检标记', value: 'giveUpCheckFlag', type: 3 };
export const APPLY_FORM_FOR_SEARCH = [
  hospitalCodeNum,
  patientID,
  patientNo,
  bedNo,
  patientType,
  enName,
  age,
  ageUnit,
  sampleTypeName,
  saleManId,
  agentName,
  isPaymentReceived,
  payMode,
  paymentOrderNo,
  diagnosis,
  transportBy,
  creatEr,
  applyDate,
  collectDate,
  receiveDate,
  telphoneNo,
  idCardNo,
  passportNo,
  nation,
  nationality,
  remark,
  address,
  sampleBarcode,
  sampleNo,
  currentNode,
  isEmer,
  reportDelayFlag,
  bloodFlag,
  giveUpCheckFlag,
];
const auditStatus = { label: '审核状态', value: 'auditStatus', type: 3 };
const explainContent = { label: '建议解释', value: 'explainContent', type: 1 };
const hospitalPathologyNo = { label: '送检单位原病理号', value: 'hospitalPathologyNo', type: 1 };
const instrId = { label: '检验仪器', value: 'instrId', type: 3 };
const lastAuditBy = { label: '终审人', value: 'lastAuditBy', type: 3 };
const lastAuditDate = { label: '终审时间', value: 'lastAuditDate', type: 4 };
const lastPrintDate = { label: '打印时间', value: 'lastPrintDate', type: 4 };
const printFlag = { label: '是否打印', value: 'printFlag', type: 3 };
const publishFlag = { label: '是否发布', value: 'publishFlag', type: 3 };
const resultModifyFlag = { label: '结果修改标记', value: 'resultModifyFlag', type: 3 };
const sampleStateId = { label: '样本性状', value: 'sampleStateId', type: 3 };
const sampleTypeId = { label: '样本类型', value: 'sampleTypeId', type: 3 };
const splitId = { label: '收样条码', value: 'splitId', type: 1 };
const telPhoneNo = { label: '电话', value: 'telPhoneNo', type: 1 };
export const REPORT_FORM_FOR_SEARCH = [
  applyDate,
  auditStatus,
  bedNo,
  collectDate,
  createDate,
  explainContent,
  resultModifyFlag,
  hospitalPathologyNo,
  idCardNo,
  instrId,
  lastAuditBy,
  lastAuditDate,
  remark,
  lastPrintDate,
  patientNo,
  patientID,
  printFlag,
  publishFlag,
  sampleStateId,
  sampleTypeId,
  splitId,
  telPhoneNo,
];
