//民族列表
export const NATIONS = [
  '汉族',
  '蒙古族',
  '回族',
  '藏族',
  '维吾尔族',
  '苗族',
  '彝族',
  '壮族',
  '布依族',
  '朝鲜族',
  '满族',
  '侗族',
  '瑶族',
  '白族',
  '土家族',
  '哈尼族',
  '哈萨克族',
  '傣族',
  '黎族',
  '傈僳族',
  '佤族',
  '畲族',
  '高山族',
  '拉祜族',
  '水族',
  '东乡族',
  '纳西族',
  '景颇族',
  '柯尔克孜族',
  '土族',
  '达斡尔族',
  '仫佬族',
  '羌族',
  '布朗族',
  '撒拉族',
  '毛南族',
  '仡佬族',
  '锡伯族',
  '阿昌族',
  '普米族',
  '塔吉克族',
  '怒族',
  '乌孜别克族',
  '俄罗斯族',
  '鄂温克族',
  '德昂族',
  '保安族',
  '裕固族',
  '京族',
  '塔塔尔族',
  '独龙族',
  '鄂伦春族',
  '赫哲族',
  '门巴族',
  '珞巴族',
  '基诺族',
];

// 邮箱后缀列表
export const EMAIL_FILL = [
  'qq.com',
  '163.com',
  '126.com',
  'sina.com',
  'hotmail.com',
  'gmail.com',
  'sohu.com',
];

// 性别列表
export const SEX_LIST = ['--', '男', '女', '--'];

// 工作性质列表
export const WORK_TYPE_LIST = [
  '全职',
  '实习',
  '兼职',
  '劳务派遣',
  '劳务外包',
  '钟点工',
  '退休返聘',
  '无类型',
];

// 工作年限列表
export const WORK_NUM_LIST = ['全部', '1年以内', '1～3年', '3～5年', '5～10年', '10年以上'];

// 星级评分文案
export const STAR_TEXT = ['很差', '一般', '满意', '非常满意', '无可挑剔'];

// 证件类型
export const CARD_TYPE = ['身份证', '港澳居民来往内地通行证', '台湾人民来往大陆通行证', '外国护照'];
//政治面貌
export const PILITICAL_CLIMATE = ['党员', '团员', '群众', '其他'];

//婚姻状态列表
// export const MARRIAGE_STUATS = ['未婚', '已婚', '离异', '丧偶', '分居'];

//户口性质
// export const CENSUS_REGISTER = [
//   '本地城镇',
//   '本地农村',
//   '外地城镇（省内）',
//   '外地农村（省内）',
//   '外地城镇（省外)',
//   '外地农村（省外）',
// ];

//紧急联系人关系
// export const EMERGENEY_CONTACT = ['父母', '配偶', '子女', '亲属', '朋友', '同事', '其他'];

// 反馈状态文字
// export const STATUS_TEXT = ['已反馈', '部分反馈', '未反馈', '面试已取消'];
// 邮箱验证
export const REG_EMAIL = /\w[-\w.+]*@([A-Za-z0-9][-A-Za-z0-9]+\.)+[A-Za-z]{2,14}/g;
export const SUFFIX = ['vip.163.com', 'vip.126.com', '188.com', '163.com', '126.com', 'yeah.net'];

export const menu = [
  {
    name: '首页',
    icon: null,
    key: '1',
    url: '/home',
    children: [],
  },
  {
    name: '委外样本管理',
    icon: null,
    url: '/home',
    key: '2',
    children: [
      {
        name: '外送样本移交',
        icon: null,
        url: '/home',
        children: [],
        key: '21',
      },
      {
        name: '外送样本对账明细',
        icon: null,
        url: '/home',
        key: '3',
        children: [
          {
            name: 'Option 3',
            icon: null,
            url: '/home',
            key: '31',
            children: [],
          },
        ],
      },
      {
        name: '外送样本对账统计',
        icon: null,
        url: '/home',
        key: '3',
        children: [
          {
            name: 'Option 3',
            icon: null,
            url: '/home',
            key: '31',
            children: [],
          },
        ],
      },
      {
        name: '外送样本对账管理',
        icon: null,
        url: '/home',
        key: '3',
        children: [
          {
            name: 'Option 3',
            icon: null,
            url: '/home',
            key: '31',
            children: [],
          },
        ],
      },
    ],
  },
  {
    name: '常规检查',
    icon: null,
    url: '/home',
    key: '2',
    children: [
      {
        name: '上机任务分配-多仪器',
        icon: null,
        url: '/home',
        children: [],
        key: '21',
      },
      {
        name: '常规检验',
        icon: null,
        url: '/home',
        key: '3',
        children: [
          {
            name: 'Option 3',
            icon: null,
            url: '/home',
            key: '31',
            children: [],
          },
        ],
      },
      {
        name: '上机任务分配',
        icon: null,
        url: '/home',
        key: '3',
        children: [
          {
            name: 'Option 3',
            icon: null,
            url: '/home',
            key: '31',
            children: [],
          },
        ],
      },
    ],
  },
  {
    key: 'setting',
    url: '/setting/index',
    name: '批量录入',
    icon: 'T8-shezhi-weixuanzhong',
    selIcon: 'T8-shezhi-xuanzhong',
    children: [],
  },
  {
    key: 'setting',
    url: '/setting/index',
    name: '批量调整结果',
    icon: 'T8-shezhi-weixuanzhong',
    selIcon: 'T8-shezhi-xuanzhong',
    children: [],
  },
  {
    key: 'setting',
    url: '/setting/index',
    name: '结果合并',
    icon: 'T8-shezhi-weixuanzhong',
    selIcon: 'T8-shezhi-xuanzhong',
    children: [],
  },
  {
    key: 'setting',
    url: '/setting/index',
    name: '检验项目选择',
    icon: 'T8-shezhi-weixuanzhong',
    selIcon: 'T8-shezhi-xuanzhong',
    children: [],
  },
  {
    key: 'setting',
    url: '/setting/index',
    name: '详情',
    icon: 'T8-shezhi-weixuanzhong',
    selIcon: 'T8-shezhi-xuanzhong',
    children: [],
  },
  {
    key: 'setting',
    url: '/setting/index',
    name: '危急值',
    icon: 'T8-shezhi-weixuanzhong',
    selIcon: 'T8-shezhi-xuanzhong',
    children: [],
  },
  {
    key: 'setting',
    url: '/setting/index',
    name: '前处理管理',
    icon: 'T8-shezhi-weixuanzhong',
    selIcon: 'T8-shezhi-xuanzhong',
    children: [
      {
        key: 'setting',
        url: '/setting/index',
        name: '样本登记',
        icon: 'T8-shezhi-weixuanzhong',
        selIcon: 'T8-shezhi-xuanzhong',
        children: [
          {
            key: 'setting',
            url: '/preProcessingMag/sampleRegistration',
            name: '样本登记列表',
            icon: 'T8-shezhi-weixuanzhong',
            selIcon: 'T8-shezhi-xuanzhong',
            children: [],
          },
          // {
          //   key: 'setting',
          //   url: '/setting/index',
          //   name: '样本新增页面',
          //   icon: 'T8-shezhi-weixuanzhong',
          //   selIcon: 'T8-shezhi-xuanzhong',
          //   children: [],
          // },
          // {
          //   key: 'setting',
          //   url: '/setting/index',
          //   name: '样本编辑页面',
          //   icon: 'T8-shezhi-weixuanzhong',
          //   selIcon: 'T8-shezhi-xuanzhong',
          //   children: [],
          // },
          {
            key: 'setting',
            url: '/setting/index',
            name: '扫码录入',
            icon: 'T8-shezhi-weixuanzhong',
            selIcon: 'T8-shezhi-xuanzhong',
            children: [],
          },
        ],
      },
      {
        key: 'setting',
        url: '/setting/index',
        name: '样本签收',
        icon: 'T8-shezhi-weixuanzhong',
        selIcon: 'T8-shezhi-xuanzhong',
        children: [
          {
            key: 'setting',
            url: '/preProcessingMag/sampleReceipt',
            name: '单个签收页面',
            icon: 'T8-shezhi-weixuanzhong',
            selIcon: 'T8-shezhi-xuanzhong',
            children: [],
          },
        ],
      },
      {
        key: 'setting',
        url: '/preProcessingMag/bloodDistributionMag',
        name: '分血管理',
        icon: 'T8-shezhi-weixuanzhong',
        selIcon: 'T8-shezhi-xuanzhong',
        children: [],
      },
    ],
  },
  {
    key: 'setting',
    url: '/setting/index',
    name: '分拣',
    icon: 'T8-shezhi-weixuanzhong',
    selIcon: 'T8-shezhi-xuanzhong',
    children: [],
  },
  {
    key: 'setting',
    url: '/setting/index',
    name: '移交',
    icon: 'T8-shezhi-weixuanzhong',
    selIcon: 'T8-shezhi-xuanzhong',
    children: [],
  },
  {
    key: 'setting',
    url: '/setting/index',
    name: '客服模块',
    icon: 'T8-shezhi-weixuanzhong',
    selIcon: 'T8-shezhi-xuanzhong',
    children: [
      {
        key: 'setting',
        url: '/setting/index',
        name: '客服交接管理',
        icon: 'T8-shezhi-weixuanzhong',
        selIcon: 'T8-shezhi-xuanzhong',
        children: [],
      },
      {
        key: 'setting',
        url: '/setting/index',
        name: '客服统计',
        icon: 'T8-shezhi-weixuanzhong',
        selIcon: 'T8-shezhi-xuanzhong',
        children: [],
      },
    ],
  },
  {
    key: 'setting',
    url: '/setting/index',
    name: '咨询管理',
    icon: 'T8-shezhi-weixuanzhong',
    selIcon: 'T8-shezhi-xuanzhong',
    children: [
      {
        key: 'setting',
        url: '/setting/index',
        name: '咨询管理登记',
        icon: 'T8-shezhi-weixuanzhong',
        selIcon: 'T8-shezhi-xuanzhong',
        children: [],
      },
      {
        key: 'setting',
        url: '/setting/index',
        name: '咨询统计',
        icon: 'T8-shezhi-weixuanzhong',
        selIcon: 'T8-shezhi-xuanzhong',
        children: [],
      },
    ],
  },
  {
    key: 'setting',
    url: '/setting/index',
    name: '加减项管理',
    icon: 'T8-shezhi-weixuanzhong',
    selIcon: 'T8-shezhi-xuanzhong',
    children: [],
  },
  {
    key: 'setting',
    url: '/setting/index',
    name: '回退管理',
    icon: 'T8-shezhi-weixuanzhong',
    selIcon: 'T8-shezhi-xuanzhong',
    children: [],
  },
  {
    key: 'setting',
    url: '/setting/index',
    name: '延迟管理',
    icon: 'T8-shezhi-weixuanzhong',
    selIcon: 'T8-shezhi-xuanzhong',
    children: [],
  },
  {
    key: 'setting',
    url: '/setting/index',
    name: '报告审核',
    icon: 'T8-shezhi-weixuanzhong',
    selIcon: 'T8-shezhi-xuanzhong',
    children: [],
  },
  {
    key: 'setting',
    url: '/setting/index',
    name: '报告单综合查询',
    icon: 'T8-shezhi-weixuanzhong',
    selIcon: 'T8-shezhi-xuanzhong',
    children: [],
  },
  {
    key: 'setting',
    url: '/setting/index',
    name: '历史报告回顾',
    icon: 'T8-shezhi-weixuanzhong',
    selIcon: 'T8-shezhi-xuanzhong',
    children: [],
  },
  {
    key: 'setting',
    url: '/setting/index',
    name: '延时报告查询',
    icon: 'T8-shezhi-weixuanzhong',
    selIcon: 'T8-shezhi-xuanzhong',
    children: [],
  },
  {
    key: 'commonMaterials',
    url: '/commonMaterials/index',
    name: '常用资料设置',
    icon: 'T8-shezhi-weixuanzhong',
    selIcon: 'T8-shezhi-xuanzhong',
    children: [
      {
        key: 'inspectionInstruments',
        url: '/commonMaterials/inspectionInstruments',
        name: '检验仪器维护',
        icon: 'T8-shezhi-weixuanzhong',
        selIcon: 'T8-shezhi-xuanzhong',
        btn: [
          {
            key: 'add',
            url: '',
            name: '新增',
            icon: 'T8-shezhi-weixuanzhong',
            selIcon: 'T8-shezhi-xuanzhong',
            children: [],
          },
          {
            key: 'edit',
            url: '',
            name: '编辑',
            icon: 'T8-shezhi-weixuanzhong',
            selIcon: 'T8-shezhi-xuanzhong',
            children: [],
          },
          {
            key: 'delete',
            url: '',
            name: '删除',
            icon: 'T8-shezhi-weixuanzhong',
            selIcon: 'T8-shezhi-xuanzhong',
            children: [],
          },
          {
            key: 'import',
            url: '',
            name: '导入',
            icon: 'T8-shezhi-weixuanzhong',
            selIcon: 'T8-shezhi-xuanzhong',
            children: [],
          },
          {
            key: 'export',
            url: '',
            name: '导出',
            icon: 'T8-shezhi-weixuanzhong',
            selIcon: 'T8-shezhi-xuanzhong',
            children: [],
          },
          {
            key: 'bind',
            url: '',
            name: '绑定',
            icon: 'T8-shezhi-weixuanzhong',
            selIcon: 'T8-shezhi-xuanzhong',
            children: [],
          },
          {
            key: 'printAdd',
            url: '',
            name: '打印新增',
            icon: 'T8-shezhi-weixuanzhong',
            selIcon: 'T8-shezhi-xuanzhong',
            children: [],
          },
          {
            key: 'printEdit',
            url: '',
            name: '打印编辑',
            icon: 'T8-shezhi-weixuanzhong',
            selIcon: 'T8-shezhi-xuanzhong',
            children: [],
          },
          {
            key: 'printDelete',
            url: '',
            name: '打印删除',
            icon: 'T8-shezhi-weixuanzhong',
            selIcon: 'T8-shezhi-xuanzhong',
            children: [],
          },
        ],
      },

      {
        key: 'basicData',
        url: '/commonMaterials/basicData',
        name: '常见资料维护',
        icon: 'T8-shezhi-weixuanzhong',
        selIcon: 'T8-shezhi-xuanzhong',
        children: [],
        btn: [
          {
            key: 'add',
            url: '',
            name: '新增',
            icon: 'T8-shezhi-weixuanzhong',
            selIcon: 'T8-shezhi-xuanzhong',
            children: [],
          },
          {
            key: 'edit',
            url: '',
            name: '编辑',
            icon: 'T8-shezhi-weixuanzhong',
            selIcon: 'T8-shezhi-xuanzhong',
            children: [],
          },
          {
            key: 'delete',
            url: '',
            name: '删除',
            icon: 'T8-shezhi-weixuanzhong',
            selIcon: '8-shezhi-xuanzhong',
            children: [],
          },
          {
            key: 'import',
            url: '',
            name: '导入',
            icon: 'T8-shezhi-weixuanzhong',
            selIcon: 'T8-shezhi-xuanzhong',
            children: [],
          },
          {
            key: 'export',
            url: '',
            name: '导出',
            icon: 'T8-shezhi-weixuanzhong',
            selIcon: 'T8-shezhi-xuanzhong',
            children: [],
          },
        ],
      },

      {
        key: 'inspectionUnit',
        url: '/commonMaterials/inspectionUnit',
        name: '送检单位维护',
        icon: 'T8-shezhi-weixuanzhong',
        selIcon: 'T8-shezhi-xuanzhong',
        children: [],
        btn: [
          {
            key: 'add',
            url: '',
            name: '新增',
            icon: 'T8-shezhi-weixuanzhong',
            selIcon: 'T8-shezhi-xuanzhong',
            children: [],
          },
          {
            key: 'edit',
            url: '',
            name: '编辑',
            icon: 'T8-shezhi-weixuanzhong',
            selIcon: 'T8-shezhi-xuanzhong',
            children: [],
          },
          {
            key: 'delete',
            url: '',
            name: '删除',
            icon: 'T8-shezhi-weixuanzhong',
            selIcon: 'T8-shezhi-xuanzhong',
            children: [],
          },
          {
            key: 'import',
            url: '',
            name: '导入',
            icon: 'T8-shezhi-weixuanzhong',
            selIcon: 'T8-shezhi-xuanzhong',
            children: [],
          },
          {
            key: 'export',
            url: '',
            name: '导出',
            icon: 'T8-shezhi-weixuanzhong',
            selIcon: 'T8-shezhi-xuanzhong',
            children: [],
          },
        ],
      },
      {
        key: 'majorGroup',
        url: '/commonMaterials/majorGroup',
        name: '专业分类维护',
        icon: 'T8-shezhi-weixuanzhong',
        selIcon: 'T8-shezhi-xuanzhong',
        children: [],
        btn: [
          {
            key: 'add',
            url: '',
            name: '新增',
            icon: 'T8-shezhi-weixuanzhong',
            selIcon: 'T8-shezhi-xuanzhong',
            children: [],
          },
          {
            key: 'edit',
            url: '',
            name: '编辑',
            icon: 'T8-shezhi-weixuanzhong',
            selIcon: 'T8-shezhi-xuanzhong',
            children: [],
          },
          {
            key: 'delete',
            url: '',
            name: '删除',
            icon: 'T8-shezhi-weixuanzhong',
            selIcon: 'T8-shezhi-xuanzhong',
            children: [],
          },
          {
            key: 'import',
            url: '',
            name: '导入',
            icon: 'T8-shezhi-weixuanzhong',
            selIcon: 'T8-shezhi-xuanzhong',
            children: [],
          },
          {
            key: 'export',
            url: '',
            name: '导出',
            icon: 'T8-shezhi-weixuanzhong',
            selIcon: 'T8-shezhi-xuanzhong',
            children: [],
          },
          {
            key: 'bind',
            url: '',
            name: '绑定',
            icon: 'T8-shezhi-weixuanzhong',
            selIcon: 'T8-shezhi-xuanzhong',
            children: [],
          },
        ],
      },
      {
        key: 'taskGroup',
        url: '/commonMaterials/taskGroup',
        name: '任务分类维护',
        icon: 'T8-shezhi-weixuanzhong',
        selIcon: 'T8-shezhi-xuanzhong',
        children: [],
        btn: [
          {
            key: 'bind',
            url: '',
            name: '绑定',
            icon: 'T8-shezhi-weixuanzhong',
            selIcon: 'T8-shezhi-xuanzhong',
            children: [],
          },
        ],
      },
      {
        key: 'manageGroup',
        url: '/commonMaterials/manageGroup',
        name: '管理分类维护',
        icon: 'T8-shezhi-weixuanzhong',
        selIcon: 'T8-shezhi-xuanzhong',
        children: [],
        btn: [
          {
            key: 'add',
            url: '',
            name: '新增',
            icon: 'T8-shezhi-weixuanzhong',
            selIcon: 'T8-shezhi-xuanzhong',
            children: [],
          },
          {
            key: 'edit',
            url: '',
            name: '编辑',
            icon: 'T8-shezhi-weixuanzhong',
            selIcon: 'T8-shezhi-xuanzhong',
            children: [],
          },
          {
            key: 'delete',
            url: '',
            name: '删除',
            icon: 'T8-shezhi-weixuanzhong',
            selIcon: 'T8-shezhi-xuanzhong',
            children: [],
          },
          {
            key: 'import',
            url: '',
            name: '导入',
            icon: 'T8-shezhi-weixuanzhong',
            selIcon: 'T8-shezhi-xuanzhong',
            children: [],
          },
          {
            key: 'export',
            url: '',
            name: '导出',
            icon: 'T8-shezhi-weixuanzhong',
            selIcon: 'T8-shezhi-xuanzhong',
            children: [],
          },
        ],
      },
      {
        key: 'applyProjectGroup',
        url: '/commonMaterials/applyProjectGroup',
        name: '申请项目分类',
        icon: 'T8-shezhi-weixuanzhong',
        selIcon: 'T8-shezhi-xuanzhong',
        children: [],
        btn: [
          {
            key: 'add',
            url: '',
            name: '新增',
            icon: 'T8-shezhi-weixuanzhong',
            selIcon: 'T8-shezhi-xuanzhong',
            children: [],
          },
          {
            key: 'edit',
            url: '',
            name: '编辑',
            icon: 'T8-shezhi-weixuanzhong',
            selIcon: 'T8-shezhi-xuanzhong',
            children: [],
          },
          {
            key: 'delete',
            url: '',
            name: '删除',
            icon: 'T8-shezhi-weixuanzhong',
            selIcon: 'T8-shezhi-xuanzhong',
            children: [],
          },
          {
            key: 'import',
            url: '',
            name: '导入',
            icon: 'T8-shezhi-weixuanzhong',
            selIcon: 'T8-shezhi-xuanzhong',
            children: [],
          },
          {
            key: 'export',
            url: '',
            name: '导出',
            icon: 'T8-shezhi-weixuanzhong',
            selIcon: 'T8-shezhi-xuanzhong',
            children: [],
          },

          {
            key: 'usingHospitalsAdd',
            url: '',
            name: '使用医院新增',
            icon: 'T8-shezhi-weixuanzhong',
            selIcon: 'T8-shezhi-xuanzhong',
            children: [],
          },
          {
            key: 'usingHospitalsDelete',
            url: '',
            name: '使用医院删除',
            icon: 'T8-shezhi-weixuanzhong',
            selIcon: 'T8-shezhi-xuanzhong',
            children: [],
          },

          {
            key: 'combinationDetailsAdd',
            url: '',
            name: '组合明细新增',
            icon: 'T8-shezhi-weixuanzhong',
            selIcon: 'T8-shezhi-xuanzhong',
            children: [],
          },
          {
            key: 'combinationDetailsDelete',
            url: '',
            name: '组合明细删除',
            icon: 'T8-shezhi-weixuanzhong',
            selIcon: 'T8-shezhi-xuanzhong',
            children: [],
          },

          {
            key: 'instrumentAdd',
            url: '',
            name: '仪器新增',
            icon: 'T8-shezhi-weixuanzhong',
            selIcon: 'T8-shezhi-xuanzhong',
            children: [],
          },
          {
            key: 'instrumentDelete',
            url: '',
            name: '仪器删除',
            icon: 'T8-shezhi-weixuanzhong',
            selIcon: 'T8-shezhi-xuanzhong',
            children: [],
          },

          {
            key: 'reportAdd',
            url: '',
            name: '报告项目新增',
            icon: 'T8-shezhi-weixuanzhong',
            selIcon: 'T8-shezhi-xuanzhong',
            children: [],
          },
          {
            key: 'reportDelete',
            url: '',
            name: '报告项目删除',
            icon: 'T8-shezhi-weixuanzhong',
            selIcon: 'T8-shezhi-xuanzhong',
            children: [],
          },

          {
            key: 'guidePriceAdd',
            url: '',
            name: '基准价格新增',
            icon: 'T8-shezhi-weixuanzhong',
            selIcon: 'T8-shezhi-xuanzhong',
            children: [],
          },
          {
            key: 'guidePriceDelete',
            url: '',
            name: '基准价格删除',
            icon: 'T8-shezhi-weixuanzhong',
            selIcon: 'T8-shezhi-xuanzhong',
            children: [],
          },
          {
            key: 'guidePriceEdit',
            url: '',
            name: '基准价格编辑',
            icon: 'T8-shezhi-weixuanzhong',
            selIcon: 'T8-shezhi-xuanzhong',
            children: [],
          },
        ],
      },
      {
        key: 'applyReportPC',
        url: '/commonMaterials/applyReportPC',
        name: '申请项目和报告项目对照',
        icon: 'T8-shezhi-weixuanzhong',
        selIcon: 'T8-shezhi-xuanzhong',
        children: [],
        btn: [
          {
            key: 'add',
            url: '',
            name: '新增',
            icon: 'T8-shezhi-weixuanzhong',
            selIcon: 'T8-shezhi-xuanzhong',
            children: [],
          },
          {
            key: 'edit',
            url: '',
            name: '编辑',
            icon: 'T8-shezhi-weixuanzhong',
            selIcon: 'T8-shezhi-xuanzhong',
            children: [],
          },
          {
            key: 'delete',
            url: '',
            name: '删除',
            icon: 'T8-shezhi-weixuanzhong',
            selIcon: 'T8-shezhi-xuanzhong',
            children: [],
          },
          {
            key: 'import',
            url: '',
            name: '导入',
            icon: 'T8-shezhi-weixuanzhong',
            selIcon: 'T8-shezhi-xuanzhong',
            children: [],
          },
          {
            key: 'export',
            url: '',
            name: '导出',
            icon: 'T8-shezhi-weixuanzhong',
            selIcon: 'T8-shezhi-xuanzhong',
            children: [],
          },
          {
            key: 'instrumentNumberAdd',
            url: '',
            name: '仪器号新增',
            icon: 'T8-shezhi-weixuanzhong',
            selIcon: 'T8-shezhi-xuanzhong',
            children: [],
          },
          {
            key: 'instrumentNumberDelete',
            url: '',
            name: '仪器号删除',
            icon: 'T8-shezhi-weixuanzhong',
            selIcon: 'T8-shezhi-xuanzhong',
            children: [],
          },
          {
            key: 'instrumentNumberEdit',
            url: '',
            name: '仪器号编辑',
            icon: 'T8-shezhi-weixuanzhong',
            selIcon: 'T8-shezhi-xuanzhong',
            children: [],
          },

          {
            key: 'referenceValueAdd',
            url: '',
            name: '参考值新增',
            icon: 'T8-shezhi-weixuanzhong',
            selIcon: 'T8-shezhi-xuanzhong',
            children: [],
          },
          {
            key: 'referenceValueDelete',
            url: '',
            name: '参考值删除',
            icon: 'T8-shezhi-weixuanzhong',
            selIcon: 'T8-shezhi-xuanzhong',
            children: [],
          },
          {
            key: 'referenceValueEdit',
            url: '',
            name: '参考值编辑',
            icon: 'T8-shezhi-weixuanzhong',
            selIcon: 'T8-shezhi-xuanzhong',
            children: [],
          },

          {
            key: 'criticalValueAdd',
            url: '',
            name: '危机值新增',
            icon: 'T8-shezhi-weixuanzhong',
            selIcon: '8-shezhi-xuanzhong',
            children: [],
          },
          {
            key: 'criticalValueDelete',
            url: '',
            name: '危机值删除',
            icon: 'T8-shezhi-weixuanzhong',
            selIcon: 'T8-shezhi-xuanzhong',
            children: [],
          },
          {
            key: 'criticalValueEdit',
            url: '',
            name: '危机值编辑',
            icon: 'T8-shezhi-weixuanzhong',
            selIcon: 'T8-shezhi-xuanzhong',
            children: [],
          },

          {
            key: 'formulaAdd',
            url: '',
            name: '计算公司新增',
            icon: 'T8-shezhi-weixuanzhong',
            selIcon: 'T8-shezhi-xuanzhong',
            children: [],
          },
          {
            key: 'formulaDelete',
            url: '',
            name: '计算公司删除',
            icon: 'T8-shezhi-weixuanzhong',
            selIcon: 'T8-shezhi-xuanzhong',
            children: [],
          },
          {
            key: 'formulaEdit',
            url: '',
            name: '计算公司编辑',
            icon: 'T8-shezhi-weixuanzhong',
            selIcon: 'T8-shezhi-xuanzhong',
            children: [],
          },

          {
            key: 'commonResultsAdd',
            url: '',
            name: '常用结果新增',
            icon: 'T8-shezhi-weixuanzhong',
            selIcon: 'T8-shezhi-xuanzhong',
            children: [],
          },
          {
            key: 'commonResultsDelete',
            url: '',
            name: '常用结果删除',
            icon: 'T8-shezhi-weixuanzhong',
            selIcon: 'T8-shezhi-xuanzhong',
            children: [],
          },
          {
            key: 'commonResultsEdit',
            url: '',
            name: '常用结果编辑',
            icon: 'T8-shezhi-weixuanzhong',
            selIcon: 'T8-shezhi-xuanzhong',
            children: [],
          },
        ],
      },
      {
        key: 'insUnitDiscount',
        url: '/commonMaterials/insUnitDiscount',
        name: '运检单位折扣维护',
        icon: 'T8-shezhi-weixuanzhong',
        selIcon: 'T8-shezhi-xuanzhong',
        children: [],
        btn: [
          {
            key: 'add',
            url: '',
            name: '新增',
            icon: 'T8-shezhi-weixuanzhong',
            selIcon: 'T8-shezhi-xuanzhong',
            children: [],
          },
          {
            key: 'edit',
            url: '',
            name: '编辑',
            icon: 'T8-shezhi-weixuanzhong',
            selIcon: 'T8-shezhi-xuanzhong',
            children: [],
          },
          {
            key: 'delete',
            url: '',
            name: '删除',
            icon: 'T8-shezhi-weixuanzhong',
            selIcon: 'T8-shezhi-xuanzhong',
            children: [],
          },
          {
            key: 'import',
            url: '',
            name: '导入',
            icon: 'T8-shezhi-weixuanzhong',
            selIcon: 'T8-shezhi-xuanzhong',
            children: [],
          },
          {
            key: 'export',
            url: '',
            name: '导出',
            icon: 'T8-shezhi-weixuanzhong',
            selIcon: 'T8-shezhi-xuanzhong',
            children: [],
          },
        ],
      },
    ],
  },
  {
    key: 'setting',
    url: '/setting/index',
    name: '设置',
    icon: 'T8-shezhi-weixuanzhong',
    selIcon: 'T8-shezhi-xuanzhong',
    children: [
      {
        key: 'globalOptionsSet',
        url: '/setting/globalOptionsSet',
        name: '全局选项设置',
        icon: 'T8-shezhi-weixuanzhong',
        selIcon: 'T8-shezhi-xuanzhong',
        children: [],
        btn: [
          {
            key: 'add',
            url: '',
            name: '新增',
            icon: 'T8-shezhi-weixuanzhong',
            selIcon: 'T8-shezhi-xuanzhong',
            children: [],
          },
          {
            key: 'edit',
            url: '',
            name: '编辑',
            icon: 'T8-shezhi-weixuanzhong',
            selIcon: 'T8-shezhi-xuanzhong',
            children: [],
          },
          {
            key: 'delete',
            url: '',
            name: '删除',
            icon: 'T8-shezhi-weixuanzhong',
            selIcon: 'T8-shezhi-xuanzhong',
            children: [],
          },
          {
            key: 'import',
            url: '',
            name: '导入',
            icon: 'T8-shezhi-weixuanzhong',
            selIcon: 'T8-shezhi-xuanzhong',
            children: [],
          },
          {
            key: 'export',
            url: '',
            name: '导出',
            icon: 'T8-shezhi-weixuanzhong',
            selIcon: 'T8-shezhi-xuanzhong',
            children: [],
          },
        ],
      },
      {
        key: 'roleMange',
        url: '/setting/roleMange',
        name: '人员管理',
        icon: 'T8-shezhi-weixuanzhong',
        selIcon: 'T8-shezhi-xuanzhong',
        children: [],
        btn: [
          {
            key: 'add',
            url: '',
            name: '新增',
            icon: 'T8-shezhi-weixuanzhong',
            selIcon: 'T8-shezhi-xuanzhong',
            children: [],
          },
          {
            key: 'edit',
            url: '',
            name: '编辑',
            icon: 'T8-shezhi-weixuanzhong',
            selIcon: 'T8-shezhi-xuanzhong',
            children: [],
          },
          {
            key: 'delete',
            url: '',
            name: '删除',
            icon: 'T8-shezhi-weixuanzhong',
            selIcon: 'T8-shezhi-xuanzhong',
            children: [],
          },
          {
            key: 'import',
            url: '',
            name: '导入',
            icon: 'T8-shezhi-weixuanzhong',
            selIcon: 'T8-shezhi-xuanzhong',
            children: [],
          },
          {
            key: 'export',
            url: '',
            name: '导出',
            icon: 'T8-shezhi-weixuanzhong',
            selIcon: 'T8-shezhi-xuanzhong',
            children: [],
          },
        ],
      },
      {
        key: 'permissionMange',
        url: '/setting/permissionMange',
        name: '权限管理',
        icon: 'T8-shezhi-weixuanzhong',
        selIcon: 'T8-shezhi-xuanzhong',
        children: [],
        btn: [
          {
            key: 'add',
            url: '',
            name: '新增',
            icon: 'T8-shezhi-weixuanzhong',
            selIcon: 'T8-shezhi-xuanzhong',
            children: [],
          },
          {
            key: 'edit',
            url: '',
            name: '编辑',
            icon: 'T8-shezhi-weixuanzhong',
            selIcon: 'T8-shezhi-xuanzhong',
            children: [],
          },
          {
            key: 'delete',
            url: '',
            name: '删除',
            icon: 'T8-shezhi-weixuanzhong',
            selIcon: 'T8-shezhi-xuanzhong',
            children: [],
          },
          {
            key: 'import',
            url: '',
            name: '导入',
            icon: 'T8-shezhi-weixuanzhong',
            selIcon: 'T8-shezhi-xuanzhong',
            children: [],
          },
          {
            key: 'export',
            url: '',
            name: '导出',
            icon: 'T8-shezhi-weixuanzhong',
            selIcon: 'T8-shezhi-xuanzhong',
            children: [],
          },
        ],
      },
      {
        key: 'organize',
        url: '/setting/organize',
        name: '角色管理',
        icon: 'T8-shezhi-weixuanzhong',
        selIcon: 'T8-shezhi-xuanzhong',
        children: [],
        btn: [
          {
            key: 'add',
            url: '',
            name: '新增',
            icon: 'T8-shezhi-weixuanzhong',
            selIcon: 'T8-shezhi-xuanzhong',
            children: [],
          },
          {
            key: 'edit',
            url: '',
            name: '编辑',
            icon: 'T8-shezhi-weixuanzhong',
            selIcon: 'T8-shezhi-xuanzhong',
            children: [],
          },
          {
            key: 'delete',
            url: '',
            name: '删除',
            icon: 'T8-shezhi-weixuanzhong',
            selIcon: 'T8-shezhi-xuanzhong',
            children: [],
          },
          {
            key: 'import',
            url: '',
            name: '导入',
            icon: 'T8-shezhi-weixuanzhong',
            selIcon: 'T8-shezhi-xuanzhong',
            children: [],
          },
          {
            key: 'export',
            url: '',
            name: '导出',
            icon: 'T8-shezhi-weixuanzhong',
            selIcon: 'T8-shezhi-xuanzhong',
            children: [],
          },
        ],
      },
      {
        key: 'roleMange',
        url: '/setting/applicationFormModel',
        name: '组件模块设置',
        icon: 'T8-shezhi-weixuanzhong',
        selIcon: 'T8-shezhi-xuanzhong',
        children: [],
      },
    ],
  },
];
